name: Apply SEMP Configuration

on:
  push:
    branches:
      - main

jobs:
  apply-semp-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Apply SEMP Configuration
      env:
        SOLACE_HOST: ${{ secrets.SOLACE_HOST }}
        VPN_NAME: ${{ secrets.VPN_NAME }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python apply_semp_config.py
        python create_client_username.py
        python configure_acl.py
